#!/usr/bin/env python3
"""Generate the Synaptic Sea system inventory: validate JSON, compute completion,
render SYSTEM_INVENTORY.md + system_map.html. Stdlib only."""
import json, sys, os, math

WEIGHTS = {"model": 15, "reachable": 15, "driven": 15, "coupled": 35, "content": 20}
_CONTENT = {"none": 0.0, "partial": 0.5, "sufficient": 1.0}

def _round(x):
    # round-half-up (Python's built-in round() is banker's rounding; the spec's
    # worked examples — 62.5 -> 63, 81.5 -> 82 — assume half-up).
    return int(math.floor(x + 0.5))

def derive_coupling(s):
    if s.get("kind") in ("infra", "tooling"):
        return "na"
    i = bool((s.get("input") or {}).get("live"))
    o = bool((s.get("output") or {}).get("live"))
    if i and o: return "closed"
    if not i and not o: return "hollow"
    return "half"

def leaf_completion(s):
    if derive_coupling(s) == "na":
        return None
    i = bool((s.get("input") or {}).get("live"))
    o = bool((s.get("output") or {}).get("live"))
    score = 0.0
    score += WEIGHTS["model"]     if s.get("model_exists") else 0
    score += WEIGHTS["reachable"] if s.get("reachable") else 0
    score += WEIGHTS["driven"]    if s.get("driven") else 0
    score += (17.5 if i else 0) + (17.5 if o else 0)
    score += WEIGHTS["content"] * _CONTENT[s.get("content", "none")]
    if not o:                      # hollow-output cap
        score = min(score, 50)
    return _round(score)

def system_completion(s):
    subs = s.get("subsystems") or []
    if subs:
        vals = [system_completion(x) for x in subs]
        vals = [v for v in vals if v is not None]
        return _round(sum(vals) / len(vals)) if vals else None
    return leaf_completion(s)

def iter_systems(data):
    def walk(s):
        yield s
        for sub in (s.get("subsystems") or []):
            yield from walk(sub)
    for top in data.get("systems", []):
        yield from walk(top)

def validate(data, root):
    errs = []
    ids = set()
    for s in iter_systems(data):
        sid = s.get("id")
        if not sid:
            errs.append(f"system missing 'id': {s.get('file') or s}")
        else:
            ids.add(sid)
    for s in iter_systems(data):
        sid = s.get("id") or "<no-id>"
        path = s.get("file")
        if path and not os.path.isfile(os.path.join(root, path)):
            errs.append(f"missing file for '{sid}': {path}")
        if s.get("kind") == "simulation" and s.get("confidence") == "?":
            errs.append(f"simulation system '{sid}' still confidence '?'")
        for edge in (s.get("integrations") or []):
            if edge.get("to") not in ids:
                errs.append(f"'{sid}' integration -> unknown id '{edge.get('to')}'")
    for loop in data.get("loops", []):
        lid = loop.get("id", "<no-id>")
        for step in loop.get("steps", []):
            if step.get("system") not in ids:
                errs.append(f"loop '{lid}' step -> unknown id '{step.get('system')}'")
    return errs

_DOT = {"closed": "🟢", "half": "🟡", "hollow": "🔴", "na": "⚪"}

def render_markdown(data):
    out = ["<!-- GENERATED by tools/build_system_inventory.py — DO NOT EDIT. "
           "Edit docs/game/inventory/system_inventory.json and re-run. -->",
           "# System Inventory\n"]
    # group all systems (top-level AND nested subsystems) by domain
    by_domain = {}
    def _add(s, parent_id, parent_domain):
        dom = s.get("domain") or parent_domain or "?"
        by_domain.setdefault(dom, []).append((s, parent_id))
        for sub in (s.get("subsystems") or []):
            _add(sub, s.get("id"), dom)
    for s in data.get("systems", []):
        _add(s, None, None)
    for domain in sorted(by_domain):
        out.append(f"## {domain}\n")
        out.append("| System | Coupling | Completion | Conf | Driven at |")
        out.append("|---|---|---|---|---|")
        for s, parent_id in by_domain[domain]:
            pct = system_completion(s)
            pct_s = "—" if pct is None else f"{pct}%"
            name = s.get("name") or s.get("id") or "?"
            if parent_id:
                name = "↳ " + name
            out.append(f"| {name} | {_DOT[derive_coupling(s)]} | "
                       f"{pct_s} | [{s.get('confidence','?')}] | {s.get('driven_at') or '—'} |")
        out.append("")
    # integration matrix
    ids = [s.get("id") for s in iter_systems(data)]
    edges = {(s.get("id"), e["to"]): e.get("health", "?")
             for s in iter_systems(data) for e in (s.get("integrations") or [])}
    out.append("## Integration matrix (row → col)\n")
    out.append("| from \\ to | " + " | ".join(ids) + " |")
    out.append("|" + "---|" * (len(ids) + 1))
    for r in ids:
        cells = [{"healthy": "🟢", "weak": "🟡", "broken": "🔴"}.get(edges.get((r, c)), "")
                 for c in ids]
        out.append(f"| {r} | " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"

def _enriched(data):
    # Flatten the whole tree (top-level systems AND nested subsystems) into map rows,
    # so subsystems appear as cards + matrix rows/cols — matching the flattened edge set.
    rows = []
    def walk(s, parent_id, parent_domain):
        dom = s.get("domain") or parent_domain or "?"
        row = {k: v for k, v in s.items() if k != "subsystems"}
        row["domain"] = dom
        row["_pct"] = system_completion(s)
        row["_coupling"] = derive_coupling(s)
        if parent_id:
            row["_parent"] = parent_id
        rows.append(row)
        for sub in (s.get("subsystems") or []):
            walk(sub, s.get("id"), dom)
    for top in data.get("systems", []):
        walk(top, None, None)
    return {"systems": rows, "loops": data.get("loops", []),
            "edges": [{"from": s.get("id"), **e}
                      for s in iter_systems(data) for e in (s.get("integrations") or [])]}

def render_html(data):
    payload = json.dumps(_enriched(data))
    # NOTE: no CDN. All CSS/JS inline. Card grid default; matrix tab; click -> detail.
    return """<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Synaptic Sea — System Map</title><style>
body{background:#0f1420;color:#d7dee8;font-family:system-ui,sans-serif;margin:0;padding:16px}
.tab{cursor:pointer;padding:6px 12px;border:1px solid #2a3340;border-radius:6px;display:inline-block;margin-right:6px}
.tab.on{background:#1f2937}
.domain{font-size:12px;letter-spacing:.6px;color:#8fb;margin:14px 0 6px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:8px}
.card{background:#1a212e;border:1px solid #2a3340;border-radius:8px;padding:9px;cursor:pointer}
.bar{height:5px;background:#222c38;border-radius:3px;margin:7px 0 4px}
.dot{width:9px;height:9px;border-radius:50%;display:inline-block;float:right}
table{border-collapse:collapse;font-size:10px}td{width:16px;height:16px;border:1px solid #0f1420}
#detail{position:fixed;right:0;top:0;width:300px;height:100%;background:#141a24;border-left:1px solid #2a3340;padding:14px;overflow:auto;display:none}
</style></head><body>
<h2>Synaptic Sea — System Map</h2>
<span class="tab on" onclick="show('cards')">Systems</span>
<span class="tab" onclick="show('matrix')">Integrations</span>
<div id="cards"></div><div id="matrix" style="display:none"></div>
<div id="detail"></div>
<script>const DATA=""" + payload + """;
const C={closed:'#3fb27f',half:'#e0a93b',hollow:'#d8584e',na:'#55606e'};
function show(w){for(const id of ['cards','matrix'])document.getElementById(id).style.display=id==w?'block':'none';
 document.querySelectorAll('.tab').forEach((t,i)=>t.className='tab'+((i==0)==(w=='cards')?' on':''));}
function detail(s){const d=document.getElementById('detail');d.style.display='block';
 d.innerHTML=`<b>${s.name||s.id}</b> <span style="color:${C[s._coupling]}">${s._coupling} ${s._pct==null?'—':s._pct+'%'}</span>
 <div style="opacity:.6;font-size:11px">${s.file}</div>
 ${s._parent?`<div style="opacity:.6;font-size:11px">subsystem of ${s._parent}</div>`:''}
 <div style="font-size:11px;margin-top:8px">model ${s.model_exists?'✓':'✗'} · reachable ${s.reachable?'✓':'✗'} · driven ${s.driven?'✓':'✗'}
 <br>in ${s.input&&s.input.live?'✓':'✗'} out ${s.output&&s.output.live?'✓':'✗'} · content ${s.content}
 <br>driven_at ${s.driven_at||'—'} · conf [${s.confidence}]</div>`;}
function cards(){const by={};DATA.systems.forEach((s,i)=>{(by[s.domain]=by[s.domain]||[]).push(i);});
 let h='';for(const dom of Object.keys(by).sort()){h+=`<div class="domain">${(dom||'?').toUpperCase()}</div><div class="grid">`;
 for(const i of by[dom]){const s=DATA.systems[i];const p=s._parent?` <span style="opacity:.5;font-size:9px">↳${s._parent}</span>`:'';
 h+=`<div class="card" data-i="${i}"><b style="font-size:12px">${s.name||s.id}</b>${p}<span class="dot" style="background:${C[s._coupling]}"></span>
 <div class="bar"><div style="width:${s._pct||0}%;height:5px;background:${C[s._coupling]};border-radius:3px"></div></div>
 <div style="font-size:10px;opacity:.6">${s._pct==null?'infra':s._pct+'%'}</div></div>`;}h+='</div>';}
 const el=document.getElementById('cards');el.innerHTML=h;
 el.querySelectorAll('.card').forEach(c=>c.addEventListener('click',()=>detail(DATA.systems[+c.dataset.i])));}
function matrix(){const ids=DATA.systems.map(s=>s.id);const e={};DATA.edges.forEach(x=>e[x.from+'|'+x.to]=x.health);
 let h='<table><tr><td></td>'+ids.map(i=>`<td style="writing-mode:vertical-rl;height:auto">${i}</td>`).join('')+'</tr>';
 for(const r of ids){h+=`<tr><td style="width:auto">${r}</td>`+ids.map(c=>{const v=e[r+'|'+c];
 return `<td style="background:${v=='healthy'?C.closed:v=='weak'?C.half:v=='broken'?C.hollow:'#1a212e'}"></td>`;}).join('')+'</tr>';}
 document.getElementById('matrix').innerHTML=h+'</table>';}
cards();matrix();
</script></body></html>"""

_COVERAGE_EXTS = (".gd", ".py")

def coverage(data, root, dirs):
    # Find source files on disk not present in the inventory. Matches .gd (the
    # runtime scripts being inventoried) and .py (so the tool's own dir is covered
    # — the unit test asserts a missing .py is reported).
    have = {s.get("file") for s in iter_systems(data)}
    missing = []
    for d in dirs:
        for dirpath, _, files in os.walk(os.path.join(root, d)):
            for fn in files:
                if fn.endswith(_COVERAGE_EXTS):
                    rel = os.path.relpath(os.path.join(dirpath, fn), root).replace("\\", "/")
                    if rel not in have:
                        missing.append(rel)
    return sorted(missing)

def main(argv):
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(root, "docs/game/inventory/system_inventory.json")
    with open(src, encoding="utf-8") as f:
        data = json.load(f)
    errs = validate(data, root)
    n = sum(1 for _ in iter_systems(data))
    verified = sum(1 for s in iter_systems(data) if s.get("confidence") == "V")
    md_path = os.path.join(root, "docs/game/inventory/SYSTEM_INVENTORY.md")
    html_path = os.path.join(root, "docs/game/inventory/system_map.html")
    RUNTIME_DIRS = ["scripts/systems", "scripts/procgen", "scripts/tools", "scripts/ui",
                    "scripts/player", "scripts/camera", "scripts/interaction", "scripts/placement"]
    if "--coverage" in argv:
        missing = coverage(data, root, RUNTIME_DIRS)
        if missing:
            for m in missing: print("ERROR: not in inventory:", m)
            return 1
        print(f"SYSTEM INVENTORY COVERAGE PASS scripts={n}")
        return 0
    # Validation gates BOTH --check and the default build: render only valid data, so a
    # malformed entry can't crash the renderers or silently write a broken file.
    if errs:
        for e in errs: print("ERROR:", e)
        return 1
    md = render_markdown(data)
    html = render_html(data)
    if "--check" in argv:
        stale = [os.path.basename(p) for p, content in ((md_path, md), (html_path, html))
                 if (open(p, encoding="utf-8").read() if os.path.isfile(p) else None) != content]
        if stale:
            print("ERROR: stale generated files:", ", ".join(stale))
            return 1
        print(f"SYSTEM INVENTORY CHECK PASS systems={n} verified={verified}")
        return 0
    open(md_path, "w", encoding="utf-8").write(md)
    open(html_path, "w", encoding="utf-8").write(html)
    print(f"SYSTEM INVENTORY BUILD PASS systems={n} verified={verified}")
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
